# terminalghost.cli.init
#
# The `terminalghost init` first-run wizard and `terminalghost uninstall`.
# init ties the pieces together: pick a shell + LLM backend, write a config,
# install the shell hook block, and optionally start the daemon / enable
# autostart. The non-interactive bits (config rendering, ollama probe) are
# module-level helpers so they can be unit-tested without a TTY.

from __future__ import annotations

import os
import shutil
import subprocess

from terminalghost.cli import profiles
from terminalghost.config import loader


def default_config_path() -> str:
    return os.path.expanduser(loader.DEFAULT_CONFIG_PATH)


def render_config(*, backend: str, ollama_model: str, color: str = "auto") -> str:
    """A clean config.toml reflecting the wizard choices (defaults fill the rest)."""
    return (
        "# TerminalGhost configuration — generated by `terminalghost init`.\n"
        "# Every key has a documented default; see the bundled config.example.toml\n"
        "# (terminalghost hook-path shows where the package lives) for the full list.\n\n"
        "[llm]\n"
        f'backend = "{backend}"\n\n'
        "[llm.ollama]\n"
        f'model = "{ollama_model}"\n\n'
        "[ui]\n"
        f'color = "{color}"\n'
    )


def ollama_status(base_url: str, model: str) -> tuple[str, list[str]]:
    """Probe a local Ollama server. Returns (state, model_names).

    state is "ready" (server up + model present), "missing" (up, model absent),
    or "down" (unreachable).
    """
    import httpx

    try:
        resp = httpx.get(f"{base_url.rstrip('/')}/api/tags", timeout=1.5)
        if resp.status_code != 200:
            return "down", []
        names = [m.get("name", "") for m in resp.json().get("models", [])]
    except Exception:  # noqa: BLE001 — any failure means "down"
        return "down", []
    present = any(n == model or n.split(":", 1)[0] == model for n in names)
    return ("ready" if present else "missing"), names


# -- commands ---------------------------------------------------------------


def cmd_init(config, config_path: str | None) -> int:
    from rich.prompt import Confirm, Prompt

    from terminalghost import __version__
    from terminalghost.ui import get_console, render_banner

    console = get_console(color=config.ui.color)
    console.print(render_banner(__version__))
    console.print(
        "\nLet's get you set up. This takes about a minute.\n", style="tg.muted"
    )

    if not console.is_terminal:
        console.print(
            "[tg.warn]init needs an interactive terminal.[/] "
            "Run it directly in your shell."
        )
        return 1

    # 1. Shell -------------------------------------------------------------
    shell = profiles.detect_shell()
    if shell:
        console.print(f"Detected shell: [tg.key]{shell}[/]")
        if not Confirm.ask("Is that right?", default=True, console=console):
            shell = None
    if not shell:
        shell = Prompt.ask(
            "Which shell?",
            choices=list(profiles.SUPPORTED_SHELLS),
            default="bash",
            console=console,
        )

    # 2. LLM backend -------------------------------------------------------
    console.print()
    console.rule("[tg.header]LLM backend")
    backend = Prompt.ask(
        "Backend", choices=["ollama", "claude"], default=config.llm.backend
        if config.llm.backend in ("ollama", "claude")
        else "ollama",
        console=console,
    )
    ollama_model = config.llm.ollama.model
    if backend == "ollama":
        ollama_model = Prompt.ask("Ollama model", default=ollama_model, console=console)
        _setup_ollama(console, config.llm.ollama.base_url, ollama_model)
    else:
        _setup_claude(console)

    # 3. Write config ------------------------------------------------------
    console.print()
    console.rule("[tg.header]Config")
    target = os.path.expanduser(config_path) if config_path else default_config_path()
    _write_config(console, target, backend=backend, ollama_model=ollama_model,
                  color=config.ui.color)
    # Reload so the daemon we start below uses the freshly written settings.
    try:
        config = loader.load_config(config_path)
    except loader.ConfigError:
        pass

    # 4. Shell integration -------------------------------------------------
    console.print()
    console.rule("[tg.header]Shell integration")
    profile = profiles.profile_path(shell)
    if Confirm.ask(f"Add TerminalGhost to [tg.key]{profile}[/]?", default=True,
                   console=console):
        result = profiles.install_block(profile, shell)
        verb = {"installed": "Added", "updated": "Updated", "already": "Already present"}
        console.print(f"[tg.success]✓[/] {verb[result]} the hook block in {profile}")
    else:
        line = profiles.hook_source_line(shell)
        console.print(f"[tg.muted]Skipped. Add this to your profile yourself:[/]\n  {line}")

    # 5. Start the daemon --------------------------------------------------
    console.print()
    if Confirm.ask("Start the daemon now?", default=True, console=console):
        from terminalghost.daemon.process import _cmd_start

        _cmd_start(config, config_path)

    # 6. Autostart ---------------------------------------------------------
    if Confirm.ask("Start automatically at login?", default=False, console=console):
        from terminalghost.cli.autostart import cmd_enable

        cmd_enable(config)

    # Done -----------------------------------------------------------------
    console.print()
    console.print("[tg.success]All set![/] Restart your shell (or open a new tab), then:")
    console.print("  run a command, then type [tg.key]??[/] to ask about it.")
    console.print("[tg.muted]Run `terminalghost doctor` any time to check things over.[/]")
    return 0


def cmd_uninstall(config, shell: str | None) -> int:
    from terminalghost.ui import get_console

    console = get_console(color=config.ui.color)
    shell = shell or profiles.detect_shell()
    if not shell:
        console.print(
            "[tg.error]Could not detect your shell.[/] "
            "Re-run with [tg.key]--shell zsh|bash|powershell[/]"
        )
        return 1
    if shell not in profiles.SUPPORTED_SHELLS:
        console.print(f"[tg.error]Unsupported shell:[/] {shell}")
        return 1

    profile = profiles.profile_path(shell)
    result = profiles.uninstall_block(profile)
    if result == "removed":
        console.print(f"[tg.success]✓[/] Removed the TerminalGhost block from [tg.key]{profile}[/]")
        console.print(
            "[tg.muted]Restart your shell to apply. Your config and history were left "
            "untouched — delete ~/.config/terminalghost and ~/.local/share/terminalghost "
            "to remove them too.[/]"
        )
    else:
        console.print(f"[tg.muted]No TerminalGhost block found in {profile}; nothing to remove.[/]")
    return 0


# -- interactive helpers ----------------------------------------------------


def _write_config(console, target: str, *, backend: str, ollama_model: str,
                  color: str) -> None:
    from rich.prompt import Confirm

    content = render_config(backend=backend, ollama_model=ollama_model, color=color)
    if os.path.exists(target):
        if not Confirm.ask(
            f"[tg.warn]{target} exists.[/] Overwrite?", default=False, console=console
        ):
            console.print("[tg.muted]Kept your existing config.[/]")
            return
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(content)
    console.print(f"[tg.success]✓[/] Wrote config to [tg.key]{target}[/]")


def _setup_ollama(console, base_url: str, model: str) -> None:
    from rich.prompt import Confirm

    state, _ = ollama_status(base_url, model)
    if state == "ready":
        console.print(f"[tg.success]✓[/] Ollama is running and [tg.key]{model}[/] is available.")
        return
    if state == "down":
        console.print(
            "[tg.warn]Ollama isn't reachable.[/] Install it from https://ollama.com, "
            "then run [tg.key]ollama serve[/]."
        )
        console.print(f"[tg.muted]Afterwards: ollama pull {model}[/]")
        return
    # missing
    if shutil.which("ollama") and Confirm.ask(
        f"Model [tg.key]{model}[/] isn't pulled yet. Pull it now?",
        default=True,
        console=console,
    ):
        console.print(f"[tg.muted]Running: ollama pull {model}[/]")
        try:
            subprocess.run(["ollama", "pull", model], check=False)
        except OSError as exc:
            console.print(f"[tg.error]Could not run ollama:[/] {exc}")
    else:
        console.print(f"[tg.muted]Pull it later with: ollama pull {model}[/]")


def _setup_claude(console) -> None:
    if os.environ.get("ANTHROPIC_API_KEY"):
        console.print("[tg.success]✓[/] ANTHROPIC_API_KEY is set.")
    else:
        console.print(
            "[tg.warn]No ANTHROPIC_API_KEY found.[/] Set it before using the daemon:\n"
            "  [tg.key]export ANTHROPIC_API_KEY=sk-ant-...[/]"
        )
    try:
        import anthropic  # noqa: F401
    except ImportError:
        console.print(
            "[tg.muted]The cloud SDK isn't installed. Reinstall with the extra:[/]\n"
            '  [tg.key]pipx install "terminalghost\\[cloud]"[/]'
        )
